# Generated by Django 2.1.5 on 2019-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncountry',
            name='country_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='spokenlanguage',
            name='language_id',
            field=models.CharField(max_length=200),
        ),
    ]
