# Generated by Django 2.1.5 on 2019-06-06 07:20

from django.db import migrations
import djongo.models.fields
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190603_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference_tag',
            field=djongo.models.fields.ArrayModelField(default=None, model_container=movies.models.PrefTag),
        ),
    ]
