# Generated by Django 2.1.5 on 2019-06-06 07:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_user_preference_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
