# Generated by Django 2.1.5 on 2019-06-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190606_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preference_tag',
        ),
    ]
