# Generated by Django 2.1.5 on 2019-06-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_user_preference_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
                ('avg_rating', models.FloatField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='movies.User')),
            ],
        ),
    ]
